### ISSUE TITLE
Need a 'refresh gui' method in gui.py

### ISSUE THREAD

**Issue by k-a-mendoza** [snmendoza/dotmaker#6]

**Comment by snmendoza** [comment]
Not needed if proper variable are used (StringVar, IntVar, etc.), which have this functionality built-in

**Comment by k-a-mendoza** [comment]
The method is less critical for refreshing GUI than it is for actually running the circle generation algorithm. I basically need to know when any variables change.

**Comment by snmendoza** [comment]
The variable will automatically change when you enter new text. Don't you only need to access them when "generate" is called?

**Comment by k-a-mendoza** [comment]
Ah. Good point. I'll close this now.
